#中心的地址是 http://localhost:8761/eureka/，
#与 eureka server 里的application.yml 中的 defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ 遥相呼应。
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name:  trend-trading-backtest-service
  zipkin:
    base-url: http://localhost:9411

feign.hystrix.enabled: true #用于开启 feign 模式的断路器

#断路器监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"